### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GuiDias13** [botcity-dev/bot-python-template#3]
depois que eu coloco o id e o nome do projeto da esse seguinte erro :

 if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'

**Comment by hhslepicka** [comment]
@GuiDias13 você pode passar quais valores esta usando para os campos?

**Comment by BrunoPeluzi** [comment]
depois que eu coloco o id e o nome do projeto da esse seguinte erro :

cookiecutter https://github.com/botcity-dev/bot-repository
cookiecutter : O termo 'cookiecutter' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente   
novamente.
No linha:1 caractere:1

**Comment by hhslepicka** [comment]
@BrunoPeluzi poderia tentar conforme as instruções neste link da documentação https://documentation.botcity.dev/tutorials/python-automations/desktop/ e me dizer se funcionou para você?

Em alguns sistemas operacionais o cookiecutter não é colocado no path como um comando. Por conta disso atualizamos a documentação para que ele seja invocado como um módulo.

**Comment by hhslepicka** [comment]
Encerrando esta issue por inatividade. @BrunoPeluzi , @GuiDias13 caso tenham alguma duvida podem reabrir.
