### ISSUE TITLE
cookiecutter : CommandNotFoundException

### ISSUE THREAD

**Issue by cindyvicentino** [botcity-dev/bot-python-template#5]
**Describe the bug**
cookiecutter : O termo 'cookiecutter' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia  do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente. No linha:1 caractere:1 + cookiecutter https://github.com/botcity-dev/bot-python-template + ~~~~~~~~~~~~     + CategoryInfo          : ObjectNotFound: (cookiecutter:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by hhslepicka** [comment]
@cindyvicentino sometimes the cookiecutter does not become available on the terminal immediately.
We updated a while ago the instructions to use a different method to create the template.
Please follow the instructions available on our documentation here: https://documentation.botcity.dev/tutorials/python-automations/desktop/#from-template-to-project

If the problem persists feel free to reopen this issue.
