### ISSUE TITLE
cookiecutter https://github.com/botcity-dev/bot-python-template  Does not work

### ISSUE THREAD

**Issue by LucasBianchini** [botcity-dev/bot-python-template#6]
**Describe the bug**

**Expected behavior**

**My Platform**

**Comment by hhslepicka** [comment]
@LucasBianchini please follow the instructions described here: https://documentation.botcity.dev/tutorials/python-automations/desktop/#from-template-to-project

With the updated instructions you no longer need Git installed.

**Comment by hhslepicka** [comment]
Closing this issue. Feel free to reopen if the problem persist.
