### ISSUE TITLE
FileNotFoundError after choosing project type.

### ISSUE THREAD

**Issue by luccasbpereira** [botcity-dev/bot-python-template#7]
When I try to create the project, it gives this error:

![image](https://user-images.githubusercontent.com/68111728/208494728-d4ea9fcf-b8ed-4a13-8d85-976690362403.png)

In this screenshot I tried in Python 3.10.9. First in 3.11.1 same error, but apparently Cookiecutter doesn't work in 3.11 anyway.
I have Python 3.8, 3.10 and 3.11 installed at same time right now.

And I don't know why this error.

**Comment by hhslepicka** [comment]
@luccasbpereira closing this issue as you managed to get it working after formatting your PC. 
Feel free to reopen.
